// Preview-only manager workflow enhancements. Smart Due removed for a simpler UI.
(() => {
'use strict';
if (window.__ABHI_MANAGER_PREVIEW__) return; window.__ABHI_MANAGER_PREVIEW__=true;
const M=v=>`₹${Math.max(0,Number(v)||0).toLocaleString('en-IN')}`;
const rem=e=>typeof publicEmiRemaining==='function'?publicEmiRemaining(e):Math.max((+e.amount||0)-(+e.paid_amount||0),0);
const paid=e=>typeof publicEmiPaid==='function'?publicEmiPaid(e):Math.min(+e.paid_amount||0,+e.amount||0);
const iso=e=>String(e?.due_date||'').slice(0,10);
const today=()=>String(publicDueData?.businessDate||new Date().toISOString()).slice(0,10);
const days=e=>/^\d{4}-\d{2}-\d{2}$/.test(iso(e))?Math.round((Date.parse(iso(e)+'T00:00:00Z')-Date.parse(today()+'T00:00:00Z'))/86400000):99999;
const active=()=>Array.isArray(loans)?loans.filter(l=>l.status==='active'):[];
function borrowerLoans(){return active().filter(l=>String(l.borrowers?.name||'').toUpperCase()===String(currentOpenFolder||'').toUpperCase())}
function enhanceBorrower(){
 if(!currentOpenFolder)return; const h=document.getElementById('currentFolderName'); if(!h)return;
 const ls=borrowerLoans();
 const r=ls.reduce((s,l)=>s+(l.emis||[]).reduce((a,e)=>a+rem(e),0),0);
 const p=ls.flatMap(l=>(l.emis||[]).map(e=>({l,e,d:days(e)}))).filter(x=>rem(x.e)>0).sort((a,b)=>a.d-b.d)[0];
 let b=document.getElementById('mgrBorrower'); if(!b){b=document.createElement('div');b.id='mgrBorrower';b.className='mgr-borrower';h.insertAdjacentElement('afterend',b)}
 b.innerHTML=`<div><small>EMI Remaining</small><b>${M(r)}</b></div><div><small>Next Due</small><b>${p?M(rem(p.e)):'₹0'}</b><span>${p?(p.d===0?'Today':p.d+' days'):'All paid'}</span></div><div><small>Active Loans</small><b>${ls.length}</b></div><div class="mgr-actions"><button data-a="timeline">History</button><button data-a="filters">Filters</button><button data-a="notes">Notes</button><button data-a="report">Report</button></div>`;
 b.querySelector('[data-a=timeline]').onclick=timeline;b.querySelector('[data-a=filters]').onclick=filters;b.querySelector('[data-a=notes]').onclick=notes;b.querySelector('[data-a=report]').onclick=report;
}
function timeline(){const items=borrowerLoans().flatMap(l=>(l.emis||[]).map(e=>({l,e}))).sort((a,b)=>iso(a.e).localeCompare(iso(b.e)));modal('🧾 Payment Timeline',items.map(x=>`<div class="mgr-row"><b>${x.l.loan_code}</b><span>${iso(x.e)||'Date not set'}</span><strong>${M(x.e.amount)}</strong><small>Paid ${M(paid(x.e))} • Remaining ${M(rem(x.e))}</small></div>`).join(''))}
function filters(){modal('🔎 Quick Filters','<div class="mgr-chips"><button onclick="window.__mgrFilter(\'due\')">Due soon</button><button onclick="window.__mgrFilter(\'overdue\')">Overdue</button><button onclick="window.__mgrFilter(\'active\')">Active</button><button onclick="window.__mgrFilter(\'paid\')">Paid</button></div><p class="mgr-help">Loan cards ko zarurat ke hisab se filter karein.</p>')}
window.__mgrFilter=t=>{document.getElementById('mgrModal')?.remove();document.querySelectorAll('#loanList .public-loan-mini-card').forEach(c=>{const txt=c.innerText.toLowerCase();c.style.display=t==='active'||(t==='overdue'&&txt.includes('overdue'))||(t==='paid'&&txt.includes('all emis paid'))||(t==='due'&&(txt.includes('days left')||txt.includes('due today')))?'':'none'})};
function notes(){const key='abhi_followup_'+currentOpenFolder,old=localStorage.getItem(key)||'';modal('📝 Follow-up Notes',`<textarea id="mgrNote" class="mgr-note" placeholder="Payment promise, call note, follow-up...">${old.replace(/</g,'&lt;')}</textarea><button class="mgr-save" onclick="localStorage.setItem('${key.replace(/'/g,'')}',document.getElementById('mgrNote').value);document.getElementById('mgrModal').remove()">Save Note</button><p class="mgr-help">Preview note sirf isi device par save hota hai.</p>`)}
function report(){const ls=borrowerLoans(),total=ls.reduce((s,l)=>s+(+l.amount||0),0),r=ls.reduce((s,l)=>s+(l.emis||[]).reduce((a,e)=>a+rem(e),0),0),pd=ls.reduce((s,l)=>s+(l.emis||[]).reduce((a,e)=>a+paid(e),0),0);modal('📊 Borrower Report',`<div class="mgr-report"><div>Loan total <b>${M(total)}</b></div><div>Paid <b>${M(pd)}</b></div><div>EMI Remaining <b>${M(r)}</b></div><div>Active loans <b>${ls.length}</b></div></div><button class="mgr-save" onclick="window.print()">Print / Export PDF</button>`)}
function modal(title,body){document.getElementById('mgrModal')?.remove();const m=document.createElement('div');m.id='mgrModal';m.className='mgr-modal';m.innerHTML=`<div class="mgr-sheet"><header><b>${title}</b><button onclick="this.closest('.mgr-modal').remove()">✕</button></header><div class="mgr-body">${body}</div></div>`;document.body.appendChild(m)}
function css(){if(document.getElementById('mgrCss'))return;const s=document.createElement('style');s.id='mgrCss';s.textContent=`.mgr-borrower{max-width:660px;margin:-8px auto 12px;display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.mgr-borrower>div:not(.mgr-actions){padding:8px;border-radius:12px;background:#f8fbff;border:1px solid #dbeafe;display:grid}.mgr-borrower small{font-size:9px;color:#64748b}.mgr-borrower b{color:#1d4ed8}.mgr-borrower span{font-size:9px}.mgr-actions{grid-column:1/-1;display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.mgr-actions button,.mgr-chips button,.mgr-save{border:0;border-radius:10px;padding:9px;background:#1a73e8;color:white;font-weight:700}.mgr-modal{position:fixed;inset:0;z-index:99999;background:#0008;display:flex;align-items:flex-end;justify-content:center}.mgr-sheet{background:white;width:min(680px,100%);max-height:85vh;border-radius:22px 22px 0 0;overflow:auto}.mgr-sheet header{position:sticky;top:0;background:white;padding:14px;display:flex;justify-content:space-between;border-bottom:1px solid #eee}.mgr-sheet header button{border:0;background:#f1f5f9;border-radius:10px;padding:7px}.mgr-body{padding:12px}.mgr-row{display:grid;grid-template-columns:1fr auto;gap:3px 10px;padding:10px;border-bottom:1px solid #eee}.mgr-row span,.mgr-row small{font-size:10px;color:#64748b}.mgr-chips{display:flex;flex-wrap:wrap;gap:8px}.mgr-note{width:100%;min-height:130px;padding:10px;border:1px solid #cbd5e1;border-radius:12px;margin-bottom:8px}.mgr-help{font-size:10px;color:#64748b}.mgr-report{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px}.mgr-report div{padding:12px;background:#f8fafc;border-radius:12px;display:grid}.dark-mode .mgr-sheet,.dark-mode .mgr-sheet header{background:#111827;color:#f8fafc}.dark-mode .mgr-borrower>div:not(.mgr-actions),.dark-mode .mgr-report div{background:#1f2937;color:#f8fafc;border-color:#334155}@media(max-width:520px){.mgr-borrower{padding:0 12px}.mgr-actions{grid-template-columns:repeat(4,1fr)}.mgr-actions button{font-size:10px;padding:8px 3px}}`;document.head.appendChild(s)}
function install(){css();document.getElementById('mgrSmartDue')?.remove();const o=window.openFolder;if(typeof o==='function'&&!o.__mgr){const w=function(...a){const r=o.apply(this,a);setTimeout(enhanceBorrower,60);return r};w.__mgr=1;window.openFolder=w}if(currentOpenFolder)enhanceBorrower()}
let n=0,t=setInterval(()=>{install();if(++n>100)clearInterval(t)},100);install();
})();